### ISSUE TITLE
CUDA OOM errors causing Ray scheduler deadlock in full sweep

### ISSUE THREAD

**Issue by xiaohan2012** [xiaohan2012/stgym#98]
## Findings

Investigated experiment [163217529480358663](http://127.0.0.1:5001/#/experiments/163217529480358663) after a full sweep on cyy2.

### Run Status Summary

| Status | Count |
|---|---|
| FINISHED | 670 |
| RUNNING | 101 |
| FAILED | 48 |
| **Total** | **819** |

### Root Cause: CUDA Out of Memory

All 48 failures share the same error:

```
CUDA error: out of memory
```

Breakdown:
- 43 failed at top-level training
- 5 failed within specific k-fold folds (fold 0, 1, or 2)

### Ray Scheduler Deadlock

The sweep is currently stuck with the following Ray autoscaler warning:

```
(autoscaler +70h8m3s) Warning: The following resource request cannot be scheduled right now:
{'GPU': 1.0, 'CPU': 5.0}. This is likely due to all cluster resources being claimed by actors.
```

**Hypothesis:** When a run crashes with CUDA OOM, the Ray actor holding that GPU may not release the memory properly. This leaves the GPU appearing "claimed" to the Ray scheduler, preventing new jobs from being dispatched — even though no useful work is being done.

## Next Steps

- Investigate which experiment configurations (model size, pooling type, batch size, etc.) are triggering OOM
- Ensure GPU memory is properly released after OOM crashes (e.g. via actor teardown or `torch.cuda.empty_cache()`)
- Consider adding memory estimation / guard before launching large configs

**Comment by xiaohan2012** [comment]
## Triage

**Type:** bug | **Priority:** P1 | **Status:** status/ready
**Blockers:** none
**Assessment:** CUDA OOMs cascade into a Ray scheduler deadlock; 101 RUNNING runs never released after full sweep. Root-cause issue overlapping with #107 and #130.

**Comment by xiaohan2012** [comment]
## Closing Note

The deadlock described in this issue was caused by memory (RAM) accumulation across Ray worker processes during long sweeps. As background RSS grew monotonically, CUDA headroom shrank — OOM kills followed, and the Ray scheduler stalled because GPU resources were not properly released by crashed actors.

This root cause was investigated and resolved in:

- **Issue #140** — Identified that RAM grows from 9 GB to 81 GB over 2.5 hours during sweeps due to Python heap fragmentation in Ray workers (`pymalloc` arenas not returned to the OS after large dataset loads).
- **PR #143** — Validated the fix: setting `STGYM_MAX_CALLS=1` (i.e., `ray.remote(max_calls=1)`) recycles workers after each task, preventing heap fragmentation buildup. Tests showed memory actually *decreased* over time with this setting, and average run time also improved.

Since the underlying memory accumulation that starved the GPU and triggered these deadlocks is now fixed, closing this issue as resolved.
